#!/usr/bin/env python
# -*- coding:utf-8 -*-  
#====#====#====#====   
#Author:
#CreatDate:
#Version: 
#====#====#====#====
from selenium.webdriver.support.select import Select
from selenium import webdriver
from time import sleep
from selenium.webdriver.common.keys import Keys

import os
from selenium.webdriver.common.action_chains import ActionChains

# dr=webdriver.Firefox()
# dr.get('https://www.taobao.com')
# e=dr.find_element_by_xpath('//[@class="ks-switchable-nav"]/li[2]')
# sleep(3)
# e.click()
# ee=dr.find_element_by_id('q')
# ee.send_keys('软件测试')
# sleep(3)
# ee.clear()
# sleep(2)
# dr.quit()

# dr=webdriver.Firefox()
# dr.get('file:///'+os.path.abspath('2.html'))
# e=dr.find_element_by_id('maker')
# print(e.get_attribute('id'))
# print(e.get_attribute('lala'))
# print(e.get_property('id'))
# print(e.get_property('lala'))

# dr=webdriver.Firefox()
# dr.get('file:///'+os.path.abspath('2.html'))
# e=dr.find_element_by_id('maker')
# print(e.text)
# ee=dr.find_element_by_id('maker2')
# ee2=dr.find_element_by_name('username')
# print(ee.get_attribute('name'))
# print(ee.size)
# print(ee.id)
# print(ee2.id)
# ee2.screenshot('./aa.png')

# dr=webdriver.Firefox()
# dr.get('file:///'+os.path.abspath('4.html'))
# e=dr.find_element_by_name('c1')
# e1=dr.find_element_by_name('c3')
# print(e.is_enabled())
# print(e1.is_enabled())

# dr=webdriver.Firefox()
# dr.get('https://www.taobao.com')
# e=dr.find_element_by_id('q')
# e.send_keys('软件测试')
# sleep(3)
# e.submit()
# print(dr.title)
# print(dr.current_url)
# sleep(3)
# dr.quit()

# dr=webdriver.Firefox()
# dr.get('https://www.baidu.com')
# e=dr.find_element_by_tag_name('body')
# ActionChains(dr).double_click(e).perform()
# sleep(5)
# dr.quit()

# dr=webdriver.Firefox()
# dr.get('https://www.baidu.com')
# e=dr.find_element_by_link_text('更多')

# dr=webdriver.Firefox()
# url='http://www.runoob.com/try/try.php?filename=jqueryui-api-droppable'
# dr.get(url)
# dr.switch_to.frame('iframeResult')
# s=dr.find_element_by_id('draggable')
# e=dr.find_element_by_id('draggable')
# ActionChains(dr).drag_and_drop(s,e).perform()

# dr=webdriver.Firefox()
# dr.get('file:///'+os.path.abspath('9.html'))
# e=dr.find_element_by_name('sel')
# sleep(3)
# listobj=Select(e)
# listobj.select_by_value('aaaa')

# dr=webdriver.Firefox()
# dr.get("https://www.baidu.com")
# e=dr.find_element_by_id('kw')
# sleep(3)
# e.send_keys('丰田车')
# sleep(3)
# e.send_keys(Keys.BACK_SPACE)
# sleep(3)
# e.send_keys(Keys.CONTROL,'a')
# sleep(3)
# e.send_keys(Keys.CONTROL,'x')
# sleep(3)
# e.send_keys(Keys.CONTROL,'v')
# sleep(3)
# e.send_keys(Keys.ENTER)

# dr=webdriver.Firefox()
# dr.get('https://www.baidu.com')
# sleep(2)
# dr.set_window_size(400,500)
# sleep(2)
# dr.minimize_window()
# sleep(2)
# dr.maximize_window()
# sleep(2)
# dr.get('https://www.taobao.com')
# sleep(2)
# dr.back()
# sleep(2)
# dr.forward()
# sleep(2)
# dr.get('https://passport.jd.com/new')
# sleep(2)
# dr.quit()

# dr=webdriver.Firefox()
# dr.get('https://www.taobao.com')
# sleep(2)
# dr.refresh()
# sleep(2)
# dr.find_element_by_link_text('天猫超市').click()
# sleep(2)
# dr.get_screenshot_as_file('1.png')
# sleep(2)
# dr.close()
# sleep(3)
# dr.quit()

# dr=webdriver.Firefox()
# dr.get('https://www.baidu.com')
# sleep(3)
# dr.find_element_by_link_text('新闻').click()
# sleep(3)
# dr.find_element_by_link_text('地图').click()
# sleep(3)
# dr.find_element_by_link_text('视频').click()
# sleep(3)
# a=dr.window_handles
# sleep(3)
# dr.switch_to.window(a[2])
# sleep(3)
# dr.close()
# dr.switch_to.window(a[1])
# sleep(3)
# dr.get_screenshot_as_file('02.png')
# dr.quit()
